# Generated by Django 4.2.30 on 2026-08-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('tag', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published_at', models.DateField(db_index=True)),
                ('attachment', models.FileField(blank=True, upload_to='announcements/')),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(max_length=100)),
                ('category_color', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('image_url', models.URLField(blank=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampusBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='campus/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='faculties/')),
                ('image_url', models.URLField(blank=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('programs', models.JSONField(blank=True, default=list)),
                ('schedule_file', models.FileField(blank=True, upload_to='schedules/')),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, upload_to='hero/')),
                ('image_url', models.URLField(blank=True)),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('acronym', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='institutions/')),
                ('image_url', models.URLField(blank=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='pages/')),
                ('image_url', models.URLField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('section', models.CharField(db_index=True, default='clinic', max_length=50)),
                ('icon', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNILUK', max_length=200)),
                ('full_name', models.CharField(default='Université Adventiste de Lukanga', max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('logo_url', models.URLField(blank=True)),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('maps_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(max_length=80)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('acronym', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='groups/')),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('full_description', models.TextField()),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/')),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('order', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('motivation', models.TextField()),
                ('document', models.FileField(blank=True, upload_to='registrations/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('review', 'En cours'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='new', max_length=20)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculty')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
