-- Initialisation éditoriale UNILUK
-- Exécuter après: python manage.py migrate
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
INSERT IGNORE INTO core_sitesettings (`id`, `name`, `full_name`, `logo`, `logo_url`, `favicon`, `address`, `phone`, `email`, `maps_url`, `facebook_url`, `youtube_url`, `instagram_url`, `x_url`, `footer_text`) VALUES
('1', 'UNILUK', 'Université Adventiste de Lukanga', '', '', '', 'Route de Lukanga, Kamina, RDC', '+243 970 000 000', 'info@uniluk.ac.cd', '', '', '', '', '', 'Université Adventiste de Lukanga — ISTA — ISTM. Former des bâtisseurs, corps et esprit, au service du Congo et du monde.');

INSERT IGNORE INTO core_heroslide (`id`, `image`, `image_url`, `tag`, `title`, `alt`, `caption`, `order`, `is_published`) VALUES
('1', '', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1600&q=85&auto=format&fit=crop', 'Excellence académique · Foi · Service', 'Campus de l\'Université Adventiste de Lukanga (UNILUK)', 'Vue principale du campus vert de l\'Université Adventiste de Lukanga UNILUK RDC', 'Formation universitaire d\'excellence au cœur de Lukanga', '0', '1'),
('2', '', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1600&q=85&auto=format&fit=crop', 'Formation Intégrale · Encadrement de proximité', 'Vie étudiante et enseignement supérieur à Lukanga', 'Étudiants diplômés et enseignants de l\'UNILUK Lukanga réunis sur le campus', 'Une communauté estudiantine dynamique et engagée', '1', '1'),
('3', '', 'https://images.unsplash.com/photo-1562774053-701939374585?w=1600&q=85&auto=format&fit=crop', 'Trois Institutions · Un Campus d\'Avenir', 'Infrastructures et amphis de l\'UNILUK, ISTA et ISTM Lukanga', 'Infrastructures modernes et salles de cours équipées de l\'UNILUK et ISTA Lukanga', 'Infrastructures pédagogiques et scientifiques modernes', '2', '1'),
('4', '', 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1600&q=85&auto=format&fit=crop', 'UNILUK · ISTA · ISTM Lukanga', 'Recherche scientifique et leadership à l\'UNILUK Lukanga', 'Séminaire et vie académique des étudiants à l\'Université Adventiste de Lukanga', 'Former des bâtisseurs intègres et compétents', '3', '1');

INSERT IGNORE INTO core_statistic (`id`, `icon`, `value`, `suffix`, `label`, `order`, `is_published`) VALUES
('1', 'fa-user-graduate', '4200', '+', 'Étudiants inscrits', '0', '1'),
('2', 'fa-building-columns', '9', '', 'Facultés & instituts', '1', '1'),
('3', 'fa-chalkboard-user', '180', '+', 'Enseignants', '2', '1'),
('4', 'fa-people-line', '6500', '+', 'Alumni', '3', '1'),
('5', 'fa-file-lines', '340', '+', 'Travaux publiés', '4', '1');

INSERT IGNORE INTO core_faculty (`id`, `code`, `name`, `image`, `image_url`, `short_description`, `description`, `programs`, `schedule_file`, `order`, `is_published`) VALUES
('1', 'THEO', 'Faculté de Théologie', '', 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=700&q=80', 'Formation pastorale et biblique, au service de l\'Église et de la société.', 'La Faculté de Théologie prépare des pasteurs, aumôniers et enseignants de religion enracinés dans les Écritures et engagés dans le service communautaire, avec un solide encadrement pratique en paroisse.', '["Licence en Théologie pastorale","Licence en Sciences religieuses","Stage pastoral encadré","Séminaires bibliques"]', '', '0', '1'),
('2', 'SEG', 'Faculté des Sciences Économiques et de Gestion', '', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=700&q=80', 'Économie, gestion des entreprises, comptabilité et finance appliquée.', 'La Faculté SEG forme des gestionnaires, économistes et comptables capables d\'accompagner le développement des entreprises et institutions publiques congolaises, avec un fort accent sur les cas pratiques et les stages.', '["Gestion financière","Comptabilité & Audit","Économie du développement","Entrepreneuriat"]', '', '1', '1'),
('3', 'SIP', 'Faculté des Sciences Infirmières & Santé Publique', '', 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=700&q=80', 'Soins infirmiers, santé communautaire et santé publique.', 'Cette faculté forme des professionnels de santé compétents et empathiques, en lien direct avec la Polyclinique de l\'UNILUK pour une pratique clinique encadrée dès les premières années.', '["Sciences infirmières générales","Santé publique","Nutrition & diététique","Stages cliniques encadrés"]', '', '2', '1'),
('4', 'PED', 'Faculté de Pédagogie Appliquée', '', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&q=80', 'Sciences de l\'éducation et formation des futurs enseignants.', 'La Faculté de Pédagogie forme des enseignants et cadres éducatifs maîtrisant à la fois les disciplines scientifiques et les méthodes pédagogiques modernes, avec des stages pratiques en écoles partenaires.', '["Pédagogie appliquée","Psychologie de l\'éducation","Didactique des sciences","Stage en école partenaire"]', '', '3', '1'),
('5', 'ISTA', 'Institut Supérieur des Techniques Appliquées (ISTA)', '', 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=700&q=80', 'Informatique, électromécanique et techniques appliquées.', 'L\'ISTA Lukanga forme des techniciens et ingénieurs de pratique en informatique, électromécanique et technologies appliquées, avec des laboratoires équipés et des projets réels en partenariat avec des entreprises locales.', '["Informatique de gestion","Réseaux & télécommunications","Électromécanique","Projets d\'entreprise"]', '', '4', '1'),
('6', 'ISTM', 'Institut Supérieur des Techniques Médicales (ISTM)', '', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=700&q=80', 'Techniques de laboratoire, imagerie médicale et kinésithérapie.', 'L\'ISTM Lukanga forme des techniciens médicaux hautement qualifiés dans les filières paramédicales, en lien étroit avec la pratique hospitalière régionale.', '["Techniques de laboratoire","Imagerie médicale","Kinésithérapie","Anesthésie-réanimation"]', '', '5', '1');

INSERT IGNORE INTO core_article (`id`, `category`, `category_color`, `title`, `slug`, `image`, `image_url`, `excerpt`, `content`, `published_at`, `order`, `is_published`) VALUES
('1', 'Vie académique', 'bg-sky-600', 'Ouverture officielle de l\'année académique 2026–2027', 'article-1', '', 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&q=80', 'Le recteur a présidé la cérémonie de rentrée devant plus de 1200 nouveaux étudiants.', 'L\'Université Adventiste de Lukanga a procédé à l\'ouverture solennelle de son année académique 2026-2027 en présence des autorités provinciales, des enseignants et de plus de 1200 nouveaux étudiants venus de toute la région du Haut-Lomami.

Dans son discours, le recteur a insisté sur l\'importance de l\'excellence académique conjuguée à l\'intégrité morale, valeurs fondatrices de l\'institution depuis sa création. La cérémonie s\'est clôturée par un culte d\'action de grâce à l\'église universitaire.', '2026-08-12', '0', '1'),
('2', 'Recherche', 'bg-emerald-600', 'Colloque scientifique sur la santé communautaire à Lukanga', 'article-2', '', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=700&q=80', 'Chercheurs et étudiants de l\'ISTM ont présenté leurs travaux devant un jury international.', 'La Faculté des Sciences Infirmières et Santé Publique, en collaboration avec l\'ISTM, a organisé un colloque scientifique réunissant plus de 40 chercheurs autour des enjeux de santé communautaire en milieu rural congolais.

Plusieurs travaux d\'étudiants ont été primés, ouvrant la voie à des publications dans des revues scientifiques partenaires.', '2026-08-02', '1', '1'),
('3', 'Partenariat', 'bg-sun-500', 'Nouveau partenariat entre l\'ISTA et des entreprises du secteur minier', 'article-3', '', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=700&q=80', 'Un accord de stage et d\'employabilité signé pour les étudiants en électromécanique.', 'L\'ISTA Lukanga a signé une convention de partenariat avec plusieurs entreprises du secteur minier du Haut-Lomami, garantissant des places de stage et des opportunités d\'embauche pour les finalistes en électromécanique et en informatique industrielle.', '2026-07-27', '2', '1'),
('4', 'Sport', 'bg-rose-500', 'L\'équipe de football UNILUK remporte le tournoi inter-universitaire', 'article-4', '', 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=700&q=80', 'Une victoire éclatante sur le terrain du campus devant des centaines de supporters.', 'L\'équipe masculine de football de l\'UNILUK a remporté le tournoi inter-universitaire du Haut-Lomami, disputé sur le terrain du campus. Une performance saluée par la direction qui encourage vivement le sport comme pilier de la formation intégrale.', '2026-07-15', '3', '1'),
('5', 'Culture', 'bg-violet-500', 'Semaine culturelle : musique, art et traditions à l\'honneur', 'article-5', '', 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=700&q=80', 'Les étudiants des différentes facultés ont animé une semaine riche en activités culturelles.', 'La traditionnelle semaine culturelle de l\'UNILUK a rassemblé les étudiants autour de concerts de chorale, d\'expositions artistiques et de soirées traditionnelles, célébrant la richesse culturelle congolaise au sein du campus.', '2026-07-03', '4', '1'),
('6', 'Communiqué', 'bg-ink', 'Rénovation du Bâtiment D et modernisation des laboratoires', 'article-6', '', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=700&q=80', 'D\'importants travaux de modernisation sont en cours sur le campus pour la rentrée.', 'La direction générale annonce le lancement de travaux de rénovation du Bâtiment D, incluant la modernisation des laboratoires d\'informatique et de sciences. Les travaux devraient s\'achever avant la rentrée académique 2026-2027.', '2026-06-28', '5', '1');

INSERT IGNORE INTO core_announcement (`id`, `tag`, `color`, `title`, `content`, `published_at`, `attachment`, `order`, `is_published`) VALUES
('1', 'Académique', 'bg-sky-600', 'Calendrier des examens du premier semestre 2026-2027', 'Le Secrétariat Général Académique porte à la connaissance de tous les étudiants que le calendrier des examens du premier semestre est désormais disponible. Les épreuves débuteront le 15 décembre 2026 et se dérouleront selon l\'horaire affiché dans chaque faculté.

Tout étudiant en ordre avec le service financier pourra retirer sa carte d\'accès aux salles d\'examen auprès du secrétariat de sa faculté.', '2026-08-10', '', '0', '1'),
('2', 'Administratif', 'bg-ink', 'Suspension temporaire des cours du vendredi 21 août', 'En raison de la retraite spirituelle annuelle du corps professoral, les cours sont suspendus le vendredi 21 août 2026 pour l\'ensemble des facultés. La reprise normale des activités académiques est prévue le lundi 24 août 2026.', '2026-08-18', '', '1', '1'),
('3', 'Finances', 'bg-sun-500', 'Rappel : échéance du deuxième versement des frais académiques', 'Le Service Financier rappelle à tous les étudiants que la date limite pour le deuxième versement des frais académiques est fixée au 30 août 2026. Passé ce délai, des pénalités de retard seront appliquées conformément au règlement financier de l\'université.', '2026-08-05', '', '2', '1'),
('4', 'Recherche', 'bg-emerald-600', 'Appel à candidatures : bourses de recherche 2027', 'La Direction de la Recherche et des Publications lance un appel à candidatures pour l\'attribution de bourses de recherche destinées aux étudiants finalistes. Les dossiers doivent être déposés au bureau de la recherche avant le 15 septembre 2026.', '2026-07-29', '', '3', '1'),
('5', 'Vie estudiantine', 'bg-violet-500', 'Élections des délégués des étudiants — session 2026', 'Le Décanat des étudiants annonce l\'ouverture des candidatures pour les élections des délégués facultaires. Les étudiants intéressés sont invités à déposer leur candidature au bureau du Décanat avant le 1er septembre 2026.', '2026-07-20', '', '4', '1');

INSERT IGNORE INTO core_institution (`id`, `acronym`, `color`, `name`, `image`, `image_url`, `short_description`, `description`, `order`, `is_published`) VALUES
('1', 'UNILUK', 'bg-sky-600', 'Université Adventiste de Lukanga', '', 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=900&q=80', 'L\'institution mère, offrant des formations en théologie, gestion, éducation et santé publique.', 'L\'Université Adventiste de Lukanga est l\'institution fondatrice du campus, offrant des formations de licence et de master dans les domaines de la théologie, des sciences économiques et de gestion, de la pédagogie appliquée et de la santé publique. Fondée sur les valeurs adventistes d\'excellence et de service, elle forme depuis plus de 30 ans des cadres reconnus dans toute la région.', '0', '1'),
('2', 'ISTA', 'bg-sun-500', 'Institut Supérieur des Techniques Appliquées', '', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=900&q=80', 'Formations techniques et technologiques : informatique, électromécanique, réseaux.', 'L\'ISTA Lukanga forme des techniciens supérieurs et ingénieurs de pratique dans les domaines de l\'informatique, de l\'électromécanique et des technologies appliquées. Ses laboratoires modernes et ses partenariats industriels garantissent une formation résolument tournée vers l\'employabilité.', '1', '1'),
('3', 'ISTM', 'bg-emerald-600', 'Institut Supérieur des Techniques Médicales', '', 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&q=80', 'Formations paramédicales : laboratoire, imagerie médicale, kinésithérapie.', 'L\'ISTM Lukanga prépare des techniciens médicaux qualifiés en laboratoire, imagerie médicale, kinésithérapie et anesthésie-réanimation. Adossé à la Polyclinique de l\'UNILUK, l\'institut garantit un apprentissage clinique concret dès les premiers stages.', '2', '1');

INSERT IGNORE INTO core_studentgroup (`id`, `acronym`, `name`, `icon`, `color`, `image`, `image_url`, `description`, `full_description`, `achievements`, `website`, `contact_email`, `order`, `is_published`) VALUES
('1', 'GACI', 'Groupe des Chercheurs et Analystes en Informatique', 'fa-laptop-code', 'bg-sky-600', '', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=700&q=80', 'Un cercle d\'étudiants passionnés de programmation, cybersécurité et intelligence artificielle.', 'Le GACI rassemble les étudiants de l\'ISTA et de l\'informatique de gestion autour de projets concrets : développement d\'applications, initiation à l\'IA et compétitions de programmation. Le groupe organise des formations hebdomadaires ouvertes à tous les étudiants intéressés par le numérique.', '["1er prix au Hackathon régional du Haut-Lomami 2025","Développement de l\'application interne de gestion des notes","Formation de plus de 150 étudiants en bureautique et code"]', '#', 'gaci@uniluk.ac.cd', '0', '1'),
('2', 'GREG', 'Groupe de Recherche en Économie et Gestion', 'fa-chart-line', 'bg-sun-500', '', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=700&q=80', 'Un espace d\'échange et de recherche pour les étudiants de la Faculté SEG.', 'Le GREG anime des séminaires, publie des notes d\'analyse économique régionale et accompagne les étudiants dans le montage de projets entrepreneuriaux. Il organise chaque année un forum entrepreneurial ouvert aux acteurs économiques de Lukanga.', '["Organisation du Forum Entrepreneurial UNILUK 2025","Publication de 12 notes d\'analyse économique régionale","Incubation de 6 projets étudiants"]', '', 'greg@uniluk.ac.cd', '1', '1'),
('3', 'CACIM', 'Cercle Académique des Cadres en Imagerie Médicale', 'fa-heart-pulse', 'bg-emerald-600', '', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=700&q=80', 'Le cercle des étudiants de l\'ISTM engagés dans la recherche paramédicale.', 'Le CACIM regroupe les étudiants de l\'ISTM autour de journées de sensibilisation sanitaire, de campagnes de dépistage communautaire et d\'ateliers pratiques en imagerie médicale, en lien direct avec la Polyclinique de l\'UNILUK.', '["Campagne de dépistage gratuit auprès de 800 habitants de Lukanga","Atelier annuel d\'imagerie médicale avancée","Partenariat avec l\'Hôpital Général de Kamina"]', '', 'cacim@uniluk.ac.cd', '2', '1');

INSERT IGNORE INTO core_campusbuilding (`id`, `name`, `description`, `image`, `image_url`, `order`, `is_published`) VALUES
('1', 'Bâtiment D', 'Salles de cours & laboratoires', '', 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80', '0', '1'),
('2', 'Bâtiment C', 'Amphithéâtres principaux', '', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80', '1', '1'),
('3', 'Bâtiment E', 'Administration & Décanat', '', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80', '2', '1'),
('4', 'Dortoir Garçons', 'Résidence universitaire hommes', '', 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80', '3', '1'),
('5', 'Dortoir Filles', 'Résidence universitaire femmes', '', 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80', '4', '1'),
('6', 'Guest House', 'Hébergement des visiteurs', '', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80', '5', '1'),
('7', 'Terrain de football', 'Complexe sportif principal', '', 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&q=80', '6', '1'),
('8', 'Terrain de basketball', 'Espace sport & loisirs', '', 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80', '7', '1');

INSERT IGNORE INTO core_service (`id`, `section`, `icon`, `title`, `description`, `order`, `is_published`) VALUES
('1', 'clinic', 'fa-stethoscope', 'Médecine générale', 'Consultations pour la communauté universitaire et environnante.', '0', '1'),
('2', 'clinic', 'fa-flask', 'Laboratoire d\'analyses', 'Analyses médicales encadrées par les étudiants de l\'ISTM.', '1', '1'),
('3', 'clinic', 'fa-house-chimney-medical', 'Maternité', 'Suivi prénatal, accouchement et soins post-natals.', '2', '1'),
('4', 'clinic', 'fa-tooth', 'Soins dentaires', 'Consultations et soins dentaires de base.', '3', '1'),
('5', 'clinic', 'fa-truck-medical', 'Urgences 24h/24', 'Service d\'urgence disponible en permanence.', '4', '1'),
('6', 'clinic', 'fa-pills', 'Pharmacie', 'Dispensation de médicaments essentiels sur place.', '5', '1');

INSERT IGNORE INTO core_galleryimage (`id`, `title`, `image`, `image_url`, `alt`, `order`, `is_published`) VALUES
('1', '', '', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80', 'Photo UNILUK', '0', '1'),
('2', '', '', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80', 'Photo UNILUK', '1', '1'),
('3', '', '', 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=80', 'Photo UNILUK', '2', '1'),
('4', '', '', 'https://images.unsplash.com/photo-1438032005730-c779502df39b?w=600&q=80', 'Photo UNILUK', '3', '1'),
('5', '', '', 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80', 'Photo UNILUK', '4', '1'),
('6', '', '', 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&q=80', 'Photo UNILUK', '5', '1'),
('7', '', '', 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80', 'Photo UNILUK', '6', '1'),
('8', '', '', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&q=80', 'Photo UNILUK', '7', '1'),
('9', '', '', 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=600&q=80', 'Photo UNILUK', '8', '1'),
('10', '', '', 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80', 'Photo UNILUK', '9', '1'),
('11', '', '', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&q=80', 'Photo UNILUK', '10', '1'),
('12', '', '', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80', 'Photo UNILUK', '11', '1');

INSERT IGNORE INTO core_testimonial (`id`, `quote`, `name`, `role`, `avatar`, `avatar_url`, `order`, `is_published`) VALUES
('1', 'Envoyer mon fils à l\'UNILUK a été la meilleure décision. Il en revient chaque week-end plus mûr, discipliné et passionné par ses études.', 'Mme Kabeya', 'Parent d\'étudiant', '', 'https://randomuser.me/api/portraits/women/68.jpg', '0', '1'),
('2', 'Diplômé de la Faculté SEG en 2018, je dirige aujourd\'hui mon propre cabinet comptable. L\'UNILUK m\'a donné bien plus que des connaissances : une véritable éthique de travail.', 'Emmanuel Tshibangu', 'Alumni, promotion 2018', '', 'https://randomuser.me/api/portraits/men/54.jpg', '1', '1'),
('3', 'L\'encadrement personnalisé et la vie spirituelle du campus ont façonné qui je suis aujourd\'hui, bien au-delà de mon diplôme d\'infirmier.', 'Josué Kanku', 'Alumni ISTM, promotion 2020', '', 'https://randomuser.me/api/portraits/men/23.jpg', '2', '1'),
('4', 'En tant que parent, je suis rassurée par le sérieux de l\'encadrement et la sécurité du campus de Lukanga.', 'Mme Ntumba', 'Parent d\'étudiante', '', 'https://randomuser.me/api/portraits/women/32.jpg', '3', '1');

INSERT IGNORE INTO core_pagecontent (`id`, `key`, `title`, `subtitle`, `content`, `image`, `image_url`, `video`, `video_url`) VALUES
('1', 'campus', 'Campus & bâtiments', '', 'Découvrez notre campus et ses infrastructures.', '', 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1400&q=80', '', 'https://vjs.zencdn.net/v/oceans.mp4'),
('2', 'eglise', 'Église Adventiste', '', 'Une vie spirituelle active au cœur du campus.', '', 'https://images.unsplash.com/photo-1438032005730-c779502df39b?w=900&q=80', '', ''),
('3', 'polyclinique', 'Polyclinique UNILUK', '', 'Des soins accessibles à la communauté universitaire et environnante.', '', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80', '', ''),
('4', 'admissions', 'Admissions 2026–2027', 'Formulaire d’inscription', 'Merci de compléter soigneusement chaque champ. Notre service des admissions vous contactera sous 72h.', '', '', '', ''),
('5', 'about', 'Une communauté d’apprentissage fondée sur l’excellence et le caractère', 'À propos de l’UNILUK', 'Née de la vision de l’Église Adventiste du Septième Jour, l’UNILUK forme des cadres compétents dans les domaines de la théologie, de la gestion, de la santé, de l’éducation et des techniques appliquées. Notre pédagogie associe rigueur scientifique, encadrement personnalisé et développement du caractère.', '', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=900&q=80', '', '');

SET FOREIGN_KEY_CHECKS=1;
